dist: trusty
sudo: false

language: node_js
node_js:
  - "13"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "viadee"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm start
